### ISSUE TITLE
Allow for geometry-based Atlas Edge filters

### ISSUE THREAD

**Issue by medercc** [osmlab/atlas#167]
**Summary**

Atlas does not currently support ingestion of OSM polygons represented as closed Ways which contain certain tags. Updating Atlas to support ingestion of OSM polygons into Atlas as `Areas` instead of `Edges` would improve one-to-one conversion between OSM and Atlas with respect to polygons, and eliminate several variations of false positive flags generated by Atlas Checks. See the examples below for details on the various ways this issue appears. 

**Example 1:** 
A closed way is tagged with` building=yes` and `highway=residential`, and is ingested into Atlas as two `Edges` because of the highway tag.  The image below shows this side by side (left=OSM, right=Atlas).
[Link to OSM Way](https://www.openstreetmap.org/way/555467267#map=19/40.99866/28.79224)

<img width="1009" alt="_2__atlas_support_for_osm_polygons_as_atlas_areas_-_quip" src="https://user-images.githubusercontent.com/33301808/42550309-de7d5712-8485-11e8-8f75-8f76f73c71e9.png">

In example 1, the closed way is an area polygon in OSM, but is being ingested in to Atlas as an `Edge` because of an erroneous highway tag.  This unintentionally removed this feature from being considered in Area-based checks in Atlas Checks, and included it in Edge-based checks.  It would be helpful to somehow check for closed ways with highway tags (even though in this case the highway tag is erroneous) and handle this by recognizing these features as `Areas` and not `Edges`.

---

**Example 2:**
A closed way is tagged with `highway=pedestrian` and `area=yes`, and is ingested into Atlas as two `Edges`.  The image below shows this side by side (left=OSM, right=Atlas).
[Link to OSM Way](https://www.openstreetmap.org/way/180834322#map=18/-33.45271/-70.67724)

<img width="1008" alt="_1__atlas_support_for_osm_polygons_as_atlas_areas_-_quip" src="https://user-images.githubusercontent.com/33301808/42550179-0056dcc4-8485-11e8-9859-4971cf4b95ac.png">

**Example 3:**
A closed way is tagged with `man_made=pier`, and is ingested into Atlas as an `Edge` by inclusion in the `Edge` filter, and by exclusion in the `Area` filter.   
[Link to OSM Way](https://www.openstreetmap.org/way/4354619#map=19/-33.85656/151.21024)

In examples 2 and 3, it is beneficial to maintain `Edge` navigability of the highway feature, but also would be an improvement to be able to somehow also recognize and interpret this as an `Area` in Atlas.

**Comment by matthieun** [comment]
Thanks for all the details! This is a common issue and ultimately defining what becomes an Edge and what does not depends on the use case for a "navigable network". The very default is to include all `highway=*` tags, but that can be improved to tailor to the use cases here. Let me focus on example 3 first:

If you build your Atlas

1. using the [atlas-generator project's Spark job](https://github.com/osmlab/atlas-generator/blob/4.0.6/src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java#L114-L116),  then you can change what becomes an Edge.
1. manually, you can alter the `AtlasLoadingOption` by [passing it a new `ConfiguredTaggableFilter edgeFilter`](https://github.com/osmlab/atlas/blob/5.1.3/src/main/java/org/openstreetmap/atlas/geography/atlas/pbf/AtlasLoadingOption.java#L261-L264).

All edge filters consist of many tag filters that must all be valid to pass. Here is [the default](https://github.com/osmlab/atlas/blob/5.1.3/src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-edge.json) one:
```javascript
{
    "filters": [
        "access->!no|motor_vehicle->yes|motorcar->yes|vehicle->yes",
        "oneway->!reversible",
        "route->ferry|man_made->pier|junction->roundabout|highway->MOTORWAY,TRUNK,PRIMARY,SECONDARY,TERTIARY,UNCLASSIFIED,RESIDENTIAL,SERVICE,MOTORWAY_LINK,TRUNK_LINK,PRIMARY_LINK,SECONDARY_LINK,TERTIARY_LINK,LIVING_STREET,PEDESTRIAN,TRACK,BUS_GUIDEWAY,RACEWAY,ROAD,FOOTWAY,BRIDLEWAY,STEPS,PATH,CYCLEWAY,ESCAPE"
    ]
}
```

Another simpler one that would fit your need for example 3:
```javascript
{
    "filters": [
        "junction->roundabout|highway->*"
    ]
}
```

However, for Examples 1 and 2, adding a specific filter against `building=*` or `area=*` would be a band-aid but not fix the bigger issue, which is the geometry. There is currently no way to filter what becomes an Edge based on geometry. I will rename the issue accordingly...

**Comment by matthieun** [comment]
Here are some new additions that seem to address this issue.
https://github.com/osmlab/atlas/pull/660
https://github.com/osmlab/atlas/pull/662
https://github.com/osmlab/atlas-generator/pull/159
