### ISSUE TITLE
Osmosis PBF to Atlas loader refactor

### ISSUE THREAD

**Issue by matthieun** [osmlab/atlas#17]
The current system to load Osmosis PBF files into the Atlas format (and perform boundary slicing and way sectioning) requires multiple passes through the PBF file, which could be faster.

It would be nice to load the PBF files once only, and then do the slicing/sectioning using the Atlas APIs directly, which would provide spatial and geometry access.

**Comment by matthieun** [comment]
This one will help for way sectioning: https://github.com/osmlab/atlas/pull/25

**Comment by MikeGost** [comment]
This will be done in 3 parts:
1. Create Raw Atlas
2. Country Slice Raw Atlas
3. Way-Section Country-Sliced Raw Atlas in a deterministic way using DynamicAtlas functionality.

**Comment by MikeGost** [comment]
@matthieun - closing as completed.
