### ISSUE TITLE
TurnRestriction Bug: NullPointerException

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas#185]
The `TurnRestriction` class is throwing a `NullPointerException` on line 332. 

It appears this is due to the `from` and `too` variable being refactored in https://github.com/osmlab/atlas/pull/181 to use use the global variables of the same name instead of the renamed local variables (now `fromMember` and `tooMember)`.

**Comment by MikeGost** [comment]
Thanks for catching this. Let me fix this.

**Comment by MikeGost** [comment]
Here's the fix: https://github.com/osmlab/atlas/pull/186

**Comment by MikeGost** [comment]
Self-merging the fix to unblock. Will let you verify and close the issue.
