### ISSUE TITLE
Relation Tree Flattening 

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas#207]
It would be great to have a function to flatten a Relation tree, à la https://github.com/osmlab/atlas-checks/pull/68. This would make it easier to create viewable representations of relations, as geoJSONs for example.

**Comment by MikeGost** [comment]
I call dibs :)

**Comment by adahn6** [comment]
Added in PR #233. @Bentleysb, this is mostly the same as the code you had in the atlas-checks PR, but I did add in recursive relationship protection :)

**Comment by Bentleysb** [comment]
The PR looks great! Nice work.

**Comment by MikeGost** [comment]
Thanks @adahn6! Will leave the task for @Bentleysb to verify and close, as needed.

**Comment by Bentleysb** [comment]
Verified that this works with [OneMemberRelationCheck](https://github.com/osmlab/atlas-checks/pull/68). This is awesome. I will be investigating how this can best be used in atlas-checks.
