### ISSUE TITLE
TaggableFilter: ! operator short circuits multi-value tests

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas#314]
The documentation for [TaggableFilters](https://github.com/osmlab/atlas/blob/dev/src/main/java/org/openstreetmap/atlas/tags/filters/README.md) states that `water->!pond,!lake` should return true for "Anything without water=pond or water=lake". In attempting to implement a similar filter, `highway->!service,!constructions`, it did not appear that this hold true. In my case, the filter would only return false if highway was equal to service, instead of service or construction. I believe this is caused by line 101 in [Taggable](https://github.com/osmlab/atlas/blob/dev/src/main/java/org/openstreetmap/atlas/tags/Taggable.java), as it always returns a boolean for a value proceeded by a `!` regardless of there being any other values to check. 
As a note, it is possible to work around this by using the filter `highway->!service&highway->!construction`.

**Comment by matthieun** [comment]
Hi @Bentleysb just to be sure. The filter you pasted says construction"s". Was that a typo while writing that issue?

**Comment by Bentleysb** [comment]
@matthieun, yes that is just a typo in the issue description.

**Comment by matthieun** [comment]
So the filter was misbehaving, but the description was wrong too. `highway->!service&highway->!construction` is the real way to go to achieve what you want. The attached PR should make that clear. Thanks!
