### ISSUE TITLE
PyAtlas -> Python3

### ISSUE THREAD

**Issue by baerbock** [osmlab/atlas#350]
Why is [PyAtlas](https://github.com/osmlab/atlas/tree/dev/pyatlas#pyatlas) still only Python2? Have you tried to automatically convert it with 2to3?

**Comment by lucaspcram** [comment]
This is a great idea - please feel free to try this yourself and contribute it back! It may be a bit before I can get around to this myself.

**Comment by lucaspcram** [comment]
@baerbock This is finally here! See #576.

**Comment by lucaspcram** [comment]
#576 is merged. Leaving this open until I am able to do a release into PyPI.

**Comment by lucaspcram** [comment]
Check PyPI for version `5.8.9` which supports Python 3.
