### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by oldcountry** [osmlab/atlas#364]
May you please publish binary releases? If not officially just for me ;) ??

I've got similar issues to https://github.com/osmlab/atlas/issues/351

**Comment by matthieun** [comment]
Binary releases are available in Maven central:
http://repo1.maven.org/maven2/org/openstreetmap/atlas/atlas/
You can find sample dependency snippets [here](https://mvnrepository.com/artifact/org.openstreetmap.atlas/atlas/5.4.1) if you want to include this in your build.

**Comment by matthieun** [comment]
Hello, @oldcountry did this resolve your issue? Let me know and I will close it.
