### ISSUE TITLE
Disable jacocoTestReport

### ISSUE THREAD

**Issue by baerbock** [osmlab/atlas#577]
Dear developers,

I'm building with OpenJDK and probably because I'm not Apple jacocoTestReport makes my build fail:

```
> Task :jacocoTestReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jacocoTestReport'.
> Unable to read execution data file /startdir/src/atlas/build/jacoco/test.exec
```

How may I disable it?

**Comment by lucaspcram** [comment]
You should be able to disable any task that is giving you trouble with the `-x` flag. Go ahead and try:
```
$ ./gradlew clean build -x jacocoTestReport
```
We'll take a look at this, I don't think you should be seeing this error. For now, let me know if that above command works. The `jacocoTestReport` task is not critical to the build so it should be fine without it.

**Comment by lucaspcram** [comment]
You should be able to disable any task that is giving you trouble with the `-x` flag. Go ahead and try:
```
$ ./gradlew clean build -x jacocoTestReport
```
I'll take a look at this, I don't think you should be seeing this error. For now, let me know if that above command works. The `jacocoTestReport` task is not critical to the build so it should be fine without it.

**Comment by matthieun** [comment]
@baerbock Please re-open if that is something you are still seeing. Thanks!
