### ISSUE TITLE
Can't install pyatlas

### ISSUE THREAD

**Issue by Mkez45634** [osmlab/atlas#612]
```
C:\Users\user\Documents\Uni\5CS024>py -m pip install pyatlas
Collecting pyatlas
  Using cached pyatlas-5.8.9-py3-none-any.whl (52 kB)
Collecting shapely==1.6.4
  Using cached Shapely-1.6.4.tar.gz (224 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-xthmnf2s\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-xthmnf2s\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-xthmnf2s\shapely\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-xthmnf2s\shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-xthmnf2s\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\user\AppData\Local\Temp\pip-install-xthmnf2s\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 373, in __init__
        self._handle = _dlopen(self._name, mode)
    FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I have added geos_c.dll to my PATH as "C:\OSGeo4W64\bin\geos_c.dll". Additonally, I tried:

`py -m pip install shapely`

which worked fine, by atlas doesn't seem to want to use it, is there a variable I need to set to change this?

**Comment by Mkez45634** [comment]
So, managed to fix it.

Had to clone the git, edit setup.py to require shapely1.7.0 as a dependency and give a version number. Additionally, I added JAVA_HOME and editied my %PATH% to add jdk/bin. Furthermore, ran gradlew cleanPyatlas buildPyatlas, but that failed, then ran the following:

`C:\Users\user\Documents\Uni\5CS024>py -m pip install C:\Users\user\atlas\pyatlas
Processing c:\users\user\atlas\pyatlas
Collecting protobuf==3.11.1
  Downloading protobuf-3.11.1-py2.py3-none-any.whl (434 kB)
     |████████████████████████████████| 434 kB 1.1 MB/s
Requirement already satisfied: shapely==1.7.0 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from pyatlas==1.0) (1.7.0)
Collecting six>=1.9
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from protobuf==3.11.1->pyatlas==1.0) (41.2.0)
Installing collected packages: six, protobuf, pyatlas
    Running setup.py install for pyatlas ... done
Successfully installed protobuf-3.11.1 pyatlas-1.0 six-1.14.0`

running the following:
`from pyatlas import pyatlas_globalfunc
pyatlas_globalfunc.hello_atlas()`

gets me

`Hello Atlas!`

So all good, probably need to check whats up with the gradle wrapper on my end.

**Comment by lucaspcram** [comment]
Hi! Thanks for posting your solution before closing the issue. Do you think your `setup.py` patch might be helpful to other users? If so, please open a PR and we can test/discuss.

**Comment by Mkez45634** [comment]
Unfortunately couldn't commit to it sorry. Feel free to add it though.

**Comment by lucaspcram** [comment]
No worries. I'll play around with this some more on my side and see if I can replicate anything. Thank you for filing the issue!
