### ISSUE TITLE
Performance expectation

### ISSUE THREAD

**Issue by chungyang** [osmlab/atlas#620]
I'm not sure if I did something, but simply running the code below takes a very long time. The pbf file is about 13MB. Is that the expected performance or I'm doing something wrong?

    public File getfile() {
        URL res = getClass().getClassLoader().getResource("rhode-island-latest.osm.pbf");
        File file = new File(res.getPath());
        System.out.print(file.getFile().length());
        return file;
    }

    public static void main(String[] args) throws URISyntaxException {
        Test t = new Test();
        File file = t.getfile();
        final Atlas rawAtlas = new RawAtlasGenerator(file).build();
        final Atlas atlas = new WaySectionProcessor(rawAtlas, AtlasLoadingOption.createOptionWithOnlySectioning()).run();
    }

**Comment by matthieun** [comment]
13 Mb for a single pbf should work, however it is on the high end to build locally.
Atlas, and way sectioning in particular use a lot of memory. What maximum memory did you allow for that job? For this I would recommend `-Xmx10G` to be safe.
If the JVM does not have enough memory, it is likely that it spends a lot of time garbage collecting.
Let me try on my side.

**Comment by matthieun** [comment]
Ok, I just tried with the atlas command, which [defaults to 2 Gb of memory](https://github.com/osmlab/atlas/blob/6.1.3/atlas-shell-tools/scripts/atlas#L120) and it completed in ~20 seconds and produced an Atlas that is ~26 Mb

**Comment by matthieun** [comment]
@chungyang If you are interested in using the `atlas` command (atlas shell tools), take a look at those instructions here: https://github.com/osmlab/atlas/tree/6.1.3/atlas-shell-tools#atlas-shell-tools

**Comment by chungyang** [comment]
Thank you for clarifying it. I think that's the issue for me. My computer just doesn't have enough memory. I'm gonna close this issue.

**Comment by matthieun** [comment]
If you want to try with a smaller area, Belize is a good candidate.
