### ISSUE TITLE
Railway crossing nodes do not exist if they don't define the shape of a way.

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas#678]
I am creating an atlas check to flag any Highways that intersect with Railways that do not have a node at the intersection. I found that railway intersection nodes that exist in the OSM pbf might not exist in the atlas file. This will cause this atlas check to incorrectly flag that a node is missing when the node actually exists in the OSM pbf.

The specific case where this happens is when the highway intersects with a railway at a node that does not determine the shape of that highway and/or railway. Below is a link to a simple example of a highway that, in OSM pbf, has four nodes (the two ends and two railway intersection nodes) and in the atlas file this same polyLine has only two locations (the two ends). 
OSM: https://www.openstreetmap.org/way/548339489
ATLAS: [Edge: id=548339489000000, startNode=5297396595000000, endNode=26525806000000, polyLine=LINESTRING (-0.3574737 49.1997678, -0.358776 49.1995892), [Tags: [last_edit_user_name => Julien Travert], [last_edit_changeset => 54812073], [last_edit_time => 1513855751000], [last_edit_user_id => 3629087], [iso_country_code => FRA], [highway => residential], [last_edit_version => 1], [oneway => yes]]]

What we would like to propose is that all OSM nodes that are intersections of two ways be added to the atlas files and be included in the polyLines that correspond to the ways that intersect. If that is too liberal of an algorithm then all highway and railway intersections be added to the atlas file.

Even though railways are not routable (today) we think that it probably makes sense to include all railway intersections so that routing functions can at least be warned about that fact that a railway intersects with the highway.

**Comment by matthieun** [comment]
Hello @atiannicelli! Thanks for submitting this issue!
I have one question for you, and also an answer.

Q. When Atlas builds an Edge from a navigable OSM Way, usually the edge's polyline contains all the shapepoints that the OSM way has. Here I am surprised that it contains only the end points. One thing I noticed is that the two railway crossings are only two months old, created July 16th, in that changeset: https://www.openstreetmap.org/changeset/88090249 ... Is it possible that your pbf file is older than this?

A. Configuring what is navigable in your Atlas generation run is easy! When running AtlasGenerator, you can use the switch [`-edgeConfiguration=/path/to/json/file`](https://github.com/osmlab/atlas-generator/blob/5.1.7/src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java#L60-L62) and it will tell the generation spark job to include anything you like as Edges. The default file [here](https://github.com/osmlab/atlas/blob/6.2.9/src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-edge.json). Updated to include railways, it would look like this (notice the `||railway->*` at the end):
```json
{
    "atlas-edge":
    {
        "taggableFilter": "access->!no||motor_vehicle->yes||motorcar->yes||vehicle->yes&oneway->!reversible&route->ferry||man_made->pier||junction->roundabout||highway->MOTORWAY,TRUNK,PRIMARY,SECONDARY,TERTIARY,UNCLASSIFIED,RESIDENTIAL,SERVICE,MOTORWAY_LINK,TRUNK_LINK,PRIMARY_LINK,SECONDARY_LINK,TERTIARY_LINK,LIVING_STREET,PEDESTRIAN,TRACK,BUS_GUIDEWAY,RACEWAY,ROAD,FOOTWAY,BRIDLEWAY,STEPS,PATH,CYCLEWAY,ESCAPE||railway->*"
    }
}
```

**Comment by adahn6** [comment]
just to add to what @matthieun, intersections like you described should be findable with the existing API pretty easily-- here's an example that should return the set of Edges that intersect with any railway tagged Lines or Edges. This may not cover your exact needs, but hopefully it provides some clarity for the API usage patterns .

```
atlas.edges(edge ->
        {
            return Iterables.isEmpty(atlas.lineItems(lineItem ->
            {
                return lineItem.getTag("railway").isPresent()
                        && lineItem.asPolyLine().intersects(edge.asPolyLine());
            }));
        });
```

**Comment by atiannicelli** [comment]
@matthieun - Thank you. I'm a bit embarrassed that I didn't see that the way's last_edit_changeset was older than the version I was editing in OSM. You are absolutely correct that the way has been altered since the pbf that I generated the atlas check from. I will close my issue. Thanks again for the explanation and taking the time to dig into it.

@adahn6 - Yes, thanks. That is very similar to the code I am using to detect the issues. My problem was that my code was detecting issues where there were non. Now I see that this is because they had been altered after the version of pbf I was using. UGH!
