### ISSUE TITLE
Enhancement of LandUse, Location and ManMade Tags

### ISSUE THREAD

**Issue by nelkapelmenka** [osmlab/atlas#768]
1. Adding getters
I have been working on a check, where I filter by tag values. Most of them contain getter functions, which helps avoid the NullPointerException. However, LandUse and Location Tags don't have one.
I am suggestion adding a `.get()` function, which would simply extract the value of the tag. 
For instance, this would change `object.get(LocationTag.KEY) != null` to `LocationTag.get(object).isPresent()`. This is already possible for some tags, such as Waterway and Natural.

2. Modifying `.isBridge()` function to include "man_made=bridge":
**First** idea is to just include it in the BridgeTag code.
**Second** idea is to create a `.isBridge()` function in the ManMadeTag and the users can implement it in this way `BridgeTag.isBridge() || ManMadeTag.isBridge()`.
**Third** idea is to combine the two above. I could add a `.isBridge()` function to the ManMadeTag AND create a `.isBridgeIncludingManMade()` function to the BridgeTag which would basically return `BridgeTag.isBridge() || ManMadeTag.isBridge()`

**Comment by Bentleysb** [comment]
The additions to LandUse and Location sound good to me. The bridge stuff is a little trickier. I think generally we want to keep tag classes self contained, so I would lean towards option two there. Perhaps something like option 3 would make sense, but placing the combined function in a tag validator class, as opposed to the tag classes themselves. I will defer to the maintainers of the repo though.

**Comment by atiannicelli** [comment]
For #2, it seems that if a feature has a `man_made=bridge` then 1) it is an area and not an edge 2) edges that cross this area should have a `bridge=yes` tag. Since these two tags specify different types of features (one is an area and one is a way) then it makes sense to go with your "Second" idea to add a ManMadeTag.isBridge()

Yup - what @Bentleysb said ^^^
