### ISSUE TITLE
Atlas 7.0.6 Release

### ISSUE THREAD

**Issue by vladlemberg** [osmlab/atlas#791]
Please release Atlas 7.0.6 version.

**Comment by vladlemberg** [comment]
@matthieun, @jwpgage. Thank you!

**Comment by adahn6** [comment]
I'll try to get a release out this week 👍

**Comment by vladlemberg** [comment]
@adahn6, do you have any update?

**Comment by vladlemberg** [comment]
@adahn6 Thank you very much!
